### ISSUE TITLE
Please add gtirb-functions

### ISSUE THREAD

**Issue by eschulte** [quicklisp/quicklisp-projects#1841]
This package implements function objects over GTIRB.  GTIRB is an intermediate representation for binary code analysis and rewriting.  The idea of functions are not first-class in GTIRB, this library provides simple function objects over top of GTIRB.

https://github.com/grammatech/gtirb-functions

Thanks!

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-05-11/failure-report/gtirb-functions.html

**Comment by eschulte** [comment]
Thanks for the report.

I've just pushed up a change to the `quicklisp` branch of the GTIRB repository which I believe should fix this build error.

**Comment by quicklisp** [comment]
I'm still getting this error in gtirb-functions (and other grammatech libraries too). What project defines the WIRE-FORMAT package?

**Comment by eschulte** [comment]
Oh sorry, that's because we now require the latest version of https://github.com/brown/protobuf (they just pushed up an important bug fix which apparently also changes the runtime interface from generated code to the library--and after https://github.com/quicklisp/quicklisp-projects/issues/1806#issuecomment-602259629 we now directly commit generated code to the quicklisp branch of https://github.com/grammatech/gtirb).

**Comment by eschulte** [comment]
WIRE-FORMAT is defined by PROTOBUF

**Comment by quicklisp** [comment]
Still getting `;   The function WIRE-FORMAT:SKIP-FIELD is called with four arguments, but wants exactly five.`

**Comment by eschulte** [comment]
So, using the latest `quicklisp` branch of the gtirb repository, every call to `skip-field` that I see has exactly 5 arguments.  All of the lisp files calling that function should be in the following directory (or it's subdirectory) https://github.com/GrammaTech/gtirb/tree/quicklisp/proto.

Can you see what file that error is thrown by?

Thanks!

**Comment by quicklisp** [comment]
There's a local issue. When pulling in gtirb I got: `both added:      proto/Section.lisp` So I have been using a stale gtirb checkout for a bit. I'm rebuilding now with a fresh cache to see if it's fixed.

**Comment by quicklisp** [comment]
Ok, looks good now.
