### ISSUE TITLE
Please add WITH-BRANCHING

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#2119]
https://github.com/phoe/with-branching
This is an implementation of macroexpand-time branching in portable Common Lisp.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-01-29/failure-report/with-branching.html

**Comment by phoe** [comment]
Fixed, thank you for the notice.

**Comment by xach** [comment]
I still get `The name "WITH-BRANCHING" does not designate any package.`

**Comment by phoe** [comment]
Ah, I need to learn to scroll down on the failure report pages! Fixed, sorry about that.

**Comment by phoe** [comment]
Closing this because it's already added.
